name: '🔂 Surge PR Preview'
description: 'Preview website in surge.sh for every pull request'
author: 'afc163'
inputs:
  surge_token:
    description: 'surge.sh token'
    default: 'f708fdcbbfdffaca6da02dca42abfd1d'
    required: false
  github_token:
    description: 'github token'
    required: true
  build:
    description: 'build scripts'
    default: |
      npm install
      npm run build
    required: false
  dist:
    description: 'dist folder to deploy'
    default: 'public'
    required: false
runs:
  using: node12
  main: 'dist/index.js'
branding:
  icon: 'monitor'
  color: 'yellow'
